# -*- coding: utf-8 -*-
"""EEW_model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jRVhfVg4sTASu32F-87wSkbOSJ1oj0Fo
"""

!wget https://github.com/krishnakanth22/MachineLearningWorks/blob/main/Earthquake/Dataset/Earthquake_Data.csv -P /content/Earthquake/

import pandas as pd
from google.colab import data_table

data_table.enable_dataframe_formatter()

df = pd.read_csv("/content/Earthquake/Earthquake_Data.csv", delimiter=r'\s+')
data_table.DataTable(df)
display(df)

new_column_names = ["Date(YYYY/MM/DD)",  "Time(UTC)", "Latitude(deg)", "Longitude(deg)", "Depth(km)", "Magnitude(ergs)",
                    "Magnitude_type", "No_of_Stations", "Gap", "Close", "RMS", "SRC", "EventID"]

df.columns = new_column_names
ts = pd.to_datetime(df["Date(YYYY/MM/DD)"] + " " + df["Time(UTC)"])
df = df.drop(["Date(YYYY/MM/DD)", "Time(UTC)"], axis=1)
df.index = ts
display(df)

df.info()

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
X = df[['Latitude(deg)', 'Longitude(deg)', 'Depth(km)', 'No_of_Stations']]
y = df['Magnitude(ergs)']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

import seaborn as sns
import matplotlib.pyplot as plt

# Select relevant features for correlation analysis
selected_features = ['Latitude(deg)', 'Longitude(deg)', 'Depth(km)', 'No_of_Stations', 'Gap', 'Close', 'RMS']
correlation_matrix = df[selected_features + ['Magnitude(ergs)']].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

import pandas as pd
import numpy as np

selected_features = ['Latitude(deg)', 'Longitude(deg)', 'Depth(km)', 'No_of_Stations', 'Gap', 'Close', 'RMS', 'Magnitude(ergs)']
selected_df = df[selected_features]
rank_df = selected_df.rank(axis=0)
differences = rank_df.diff()
differences = differences.dropna()
squared_differences = differences ** 2
sum_squared_diff = squared_differences.sum()
n = len(selected_df)
spearman_corr_coeff = 1 - (6 * sum_squared_diff.sum()) / (n * (n**2 - 1))
print("Spearman's correlation coefficient:", spearman_corr_coeff)

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate Spearman's correlation matrix
spearman_corr_matrix = selected_df.corr(method='spearman')
# Plot the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(spearman_corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Spearman\'s Correlation Matrix')
plt.show()

