# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcS98JX2EzRU-YB6FW1vjU1_jajavZbo
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
file_path = '/content/drive/MyDrive/Earthquake_K_Net/KNet_Tc_Pd_ManuallyPlusKalkan_1996.csv'
df = pd.read_csv(file_path)

df.info()

import pandas as pd
df1 = df.iloc[1:1000, 5]
print(df1)

print(df)

file_path = '/content/drive/MyDrive/Earthquake_K_Net/1996/19960523183600.knt/IWT0039605231836.UD'

with open(file_path, 'r') as file:
    contents = file.read()

print(contents)

lines = contents.split("\n")
memo_index = None
for i, line in enumerate(lines):
    if "Memo." in line:
        memo_index = i
        break
if memo_index is not None:
    memo_data = []
    memo_line_index = memo_index + 1
    while memo_line_index < len(lines) and lines[memo_line_index].strip():
        memo_data.extend(lines[memo_line_index].strip().split())
        memo_line_index += 1

    memo_array = [int(value) for value in memo_data]

    print("Memo.")
    print(memo_array)

print  (len(memo_array))

ud_lines = contents.split('\n')
for line in ud_lines:
    if 'Mag.' and '' in line:
        mag_value = line.split()[-1]
        print("Magnitude:", mag_value)
        break

