# -*- coding: utf-8 -*-
"""Feature_Engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcS98JX2EzRU-YB6FW1vjU1_jajavZbo
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Earthquake_K_Net/1996/19960523183600.knt/IWT0039605231836.UD'

with open(file_path, 'r') as file:
    contents = file.read()

print(contents)

"""## Memo. Data in Single Array"""

lines = contents.split("\n")
memo_data = []
in_memo_section = False

for line in lines:
    if "Memo." in line:
        in_memo_section = True
        continue
    if in_memo_section and line.strip():
        memo_data.extend(line.strip().split())
memo_array = [int(value) for value in memo_data]
print(memo_array)

"""## Unstructure Data/UD to Variables"""

# Assuming unstructured_data contains your unstructured data string

ud_lines = contents.split('\n')

Max_Acc = None
Mag_value = None
Origin_Time = None
Lat = None
Long = None
Depth = None
Station_Code = None
Station_Lat = None
Station_Long = None
Station_Height = None
Record_Time = None
Sampling_Freq = None
Duration = None
Dir_value = None
Scale_Factor_Numerator = None
Scale_Factor_Denominator = None
Last_Correction = None

for line in ud_lines:
    if 'Max. Acc. (gal)' in line:
        Max_Acc = float(line.split()[-1])
    elif 'Mag.' in line:
        Mag_value = float(line.split()[-1])
    elif 'Origin Time' in line:
        Origin_Time = line.split('       ')[-1].strip()
    elif 'Lat.' in line:
        Lat = float(line.split()[-1])
    elif 'Long.' in line:
        Long = float(line.split()[-1])
    elif 'Depth. (km)' in line:
        Depth = float(line.split()[-1])
    elif 'Station Code' in line:
        Station_Code = line.split()[-1]
    elif 'Station Lat.' in line:
        Station_Lat = float(line.split()[-1])
    elif 'Station Long.' in line:
        Station_Long = float(line.split()[-1])
    elif 'Station Height(m)' in line:
        Station_Height = float(line.split()[-1])
    elif 'Record Time' in line:
        Record_Time = line.split('       ')[-1].strip()
    elif 'Sampling Freq(Hz)' in line:
        Sampling_Freq = int(line.split()[-1].split('Hz')[0])
    elif 'Duration Time(s)' in line:
        Duration = int(line.split()[-1])
    elif 'Dir.' in line:
        Dir_value = line.split()[-1]
    elif 'Scale Factor' in line:
        Scale_Factor_Numerator = float(line.split()[2].split('(')[0])
        Scale_Factor_Denominator = float(line.split('/')[-1])
    elif 'Last Correction' in line:
        Last_Correction = line.split('       ')[-1].strip()

print("Max_Acc:", Max_Acc)
print("Mag_value:", Mag_value)
print("Origin_Time:", Origin_Time)
print("Lat:", Lat)
print("Long:", Long)
print("Depth:", Depth)
print("Station_Code:", Station_Code)
print("Station_Lat:", Station_Lat)
print("Station_Long:", Station_Long)
print("Station_Height:", Station_Height)
print("Record_Time:", Record_Time)
print("Sampling_Freq:", Sampling_Freq)
print("Duration:", Duration)
print("Dir_value:", Dir_value)
print("Scale_Factor_Numerator:", Scale_Factor_Numerator)
print("Scale_Factor_Denominator:", Scale_Factor_Denominator)
print("Last_Correction:", Last_Correction)